language: c
sudo: required
install: bash -ex .travis-ocaml.sh
script: "opam $(opam config env); make"
env:
  # - OCAML_VERSION=4.02
  # - OCAML_VERSION=4.03
  # - OCAML_VERSION=4.04
  # - OCAML_VERSION=4.05
  - OCAML_VERSION=4.06
  - OCAML_VERSION=4.07
os:
  - linux
  # - osx
