dist: xenial
sudo: required
addons:
  apt:
    sources:
    - ppa:mc3man/trusty-media
    packages:
    - xvfb
    - x11-apps
    - imagemagick
    - ffmpeg
install:
  - bash -ex .travis-ocaml.sh
  - eval $(opam env); sh setup-opam
script:
  - sh ci/build.sh
env:
  # - OCAML_VERSION=4.02 LABLGTK=lablgtk
  # - OCAML_VERSION=4.03
  # - OCAML_VERSION=4.04
  # - OCAML_VERSION=4.05
  - OCAML_VERSION=4.07 LABLGTK=lablgtk
  - OCAML_VERSION=4.07 LABLGTK=lablgtk3

os:
  - linux
  - osx
  
