language: c
sudo: required
install:
  - bash -ex .travis-ocaml.sh
  - eval $(opam env); sh setup-opam
script:
  # - eval $(opam env); make
  - eval $(opam env); dune build
  # TODO: linux only
  - curl -u $AUTH -fsSLO https://mamewo.ddo.jp/private/gdrive
  - chmod +x gdrive
  - curl -fsSLO https://raw.githubusercontent.com/mamewotoko/xvfb-screenshooter/master/xvfb-screenshooter.sh
  - chmod +x xvfb-screenshooter.sh
  - "./xvfb-screenshooter.sh timeout 10s dune exec src/main.exe"
  - sh ci/upload.sh
  
env:
  # - OCAML_VERSION=4.02
  # - OCAML_VERSION=4.03
  # - OCAML_VERSION=4.04
  # - OCAML_VERSION=4.05
  - OCAML_VERSION=4.06
  - OCAML_VERSION=4.07
os:
  - linux
#  - osx
