dist: xenial
sudo: required
addons:
  apt:
    sources:
    - ppa:mc3man/trusty-media
    packages:
    - xvfb
    - x11-apps
    - imagemagick
    - ffmpeg
install:
  - bash -ex .travis-ocaml.sh
  - eval $(opam env); sh setup-opam
script:
  - sh build.sh
env:
  # - OCAML_VERSION=4.02
  # - OCAML_VERSION=4.03
  # - OCAML_VERSION=4.04
  # - OCAML_VERSION=4.05
  - OCAML_VERSION=4.06
  - OCAML_VERSION=4.07

  - LABLGTK=lablgtk
  - LABLGTK=lablgtk2
  - LABLGTK=lablgtk3
os:
  - linux
  - osx
  
