#! /bin/bash
# ocaml4.07.0
if [ -z "$LABLGTK" ]; then
    LABLGTK=lablgtk
fi 

if [ "$(uname)" = Darwin ]; then
    case "$LABLGTK" in
        lablgtk)
            brew install gtk+;;
        lablgtk3)
            brew install gtk+3;;
    esac
else
    # ubuntu
    case "$LABLGTK" in
        lablgtk)
            sudo apt-get install -y libgtk2.0-dev;;
        lablgtk3)
            sudo apt-get install -y libexpat1-dev libgtk-3-dev;;
    esac
fi

opam install -y depext
opam depext -y conf-m4.1
opam install -y $LABLGTK ocamlfind dune
# eval $(opam env)
