name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build lablgtk
      run: |
        bash -ex .travis-ocaml.sh
        eval $(opam env)
        ./setup.sh
        make
        # check
        ls -l gtk_app
      env:
        OCAML_VERSION: 4.11
        TRAVIS_OS_NAME: linux
        TRAVIS_DIST: focal

  build_dune:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build lablgtk
      run: |
        bash -ex .travis-ocaml.sh
        eval $(opam env)
        ./setup.sh
        dune build src/main.exe
        # check
        ls -l ./_build/default/src/main.exe
      env:
        OCAML_VERSION: 4.11
        TRAVIS_OS_NAME: linux
        TRAVIS_DIST: focal
